version: "3.9"


services:


    frontend-client:
      build:
        context: ./apps/frontend-client
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
    db:
      build:
        context: ./db
        dockerfile: Dockerfile
      ports:
        - "5432:5432"
      volumes:
        - pg_data:/var/lib/postgresql/data
      env_file:
        - .env.development
        - .env.production
volumes:
  pg_data:
