#!/bin/bash

set -e 
psql -v ON_ERROR_STOP=1 --username postgres --dbname postgres <<-EOSQL
CREATE USER $TUNA_DB_USER WITH PASSWORD '$TUNA_DB_PASS';
CREATE DATABASE $TUNA_DB_NAME;
GRANT ALL PRIVILEGES ON DATABASE $TUNA_DB_NAME TO $TUNA_DB_USER;
EOSQL
