#!/bin/bash

set -e
psql -v ON_ERROR_STOP=1 --username postgres --dbname postgres <<-EOSQL
    CREATE USER $TUNA_DB_USER WITH PASSWORD '$TUNA_DB_PASS';
    CREATE DATABASE $TUNA_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $TUNA_DB_NAME TO $TUNA_DB_USER;
    \c $TUNA_DB_NAME postgres
    GRANT ALL ON SCHEMA public TO $TUNA_DB_USER;
    CREATE USER $KEYCLOAK_DB_USER WITH PASSWORD '$KEYCLOAK_DB_PASS';
    CREATE DATABASE $KEYCLOAK_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DB_NAME TO $KEYCLOAK_DB_USER;
    \c $KEYCLOAK_DB_NAME postgres
    GRANT ALL ON SCHEMA public TO $KEYCLOAK_DB_USER;
EOSQL
