name: Docker Image CI

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  TUNA_DB_NAME: tuna_db
  TUNA_DB_USER: tuna_user
  TUNA_DB_PASS: itsatunasecret
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the docker compose stack
        run: source .env.development && docker compose up

      - name: Move to api-gateway
        working-directory: services/api-gateway
        run: npm install && npm run test
